feat(connect): add option for multiple account select
perawallet/connect pull request #111
Opened 2023-03-07 11:20 UTC by yigiterdev

2023-03-10 11:47 UTC, mucahit requested changes
@yigiterdev Thanks! I have a couple of comments

1. Let's rename the flag to `shouldSelectSingleAccount:boolean = false`

```diff
- allowToSelectMultipleAccounts
+ shouldSelectSingleAccount
```

2. The same flag also should be sent to the Web Wallet so that we can have the same functionality on both applications. _The way you send the flag to Mobile Wallet is seems correct by the way._

3. Let's have an optional options parameter for the `connect` method to reduce possible future breaking changes over there. 

```diff
- connect(allowToSelectMultipleAccounts?: boolean)
+ connect({shouldSelectSingleAccount}: PeraWalletConnectMethodOptions = {})
```

4. And finally let's document the new option in the related Readme section.

2023-03-13 11:41 UTC, mucahit reviewed
Thanks!

2023-03-13 11:41 UTC, mucahit commented on src/modal/peraWalletConnectModalUtils.ts
> +      const newURI = `${uri}&algorand=true&allowToSelectMultipleAccounts=${modalConfig.shouldSelectSingleAccount}`;
```suggestion
      const newURI = `${uri}&algorand=true&shouldSelectSingleAccount=${modalConfig.shouldSelectSingleAccount}`;
```

2023-03-15 11:52 UTC, mucahit commented
Waiting for the Readme change to merge this @yigiterdev

2023-03-15 12:02 UTC, yigiterdev commented
Readme updated. @mucahit

2023-03-15 14:25 UTC, mucahit approved these changes

2023-03-15 14:26 UTC, merged