feat: Add modal for transaction sign guidance
perawallet/connect pull request #21
Opened 2022-07-06 13:46 UTC by yigiterdev

- Ticket: https://linear.app/hipo/issue/PWEB-18/connect-modal-for-transaction-sign-guidance

<img width="482" alt="image" src="https://user-images.githubusercontent.com/5108459/177796034-48197c18-f5c7-4b11-860d-4acde23336d0.png">

2022-07-06 15:30 UTC, mucahit commented
I think we should have an option to disable the toast, it can be enabled by default. I'm pretty sure some of the dApps are handling the guidance on their own. 

What do you think? @yigiterdev

2022-07-07 07:22 UTC, yigiterdev commented
> I think we should have an option to disable the toast, it can be enabled by default. I'm pretty sure some of the dApps are handling the guidance on their own.
> 
> What do you think? @yigiterdev

I added to `PeraWalletConnectOptions`. I'm not sure this is the best way, but here's how to use it.

`const peraWallet = new PeraWalletConnect({
  shouldShowSignTxnToast: false
});`

BTW, `shouldShowSignTxnToast`'s default is `true`. If that's okay, it might be good to add it to the readme.

2022-07-07 08:46 UTC, mucahit requested changes
thanks!! 🎉 

Let's also document `shouldShowSignTxnToast` option in the Readme

2022-07-07 08:46 UTC, mucahit commented on src/modal/peraWalletConnectModalUtils.tsx
> +const PERA_WALLET_SIGN_TXN_TOAST = "pera-wallet-sign-txn-toast";
```suggestion
const PERA_WALLET_SIGN_TXN_TOAST_ID = "pera-wallet-sign-txn-toast";
```

2022-07-07 08:46 UTC, mucahit commented on src/modal/peraWalletConnectModalUtils.tsx
> + * Creates a PeraWalletRedirectModal instance and renders it on the DOM.
Let's update the JSDoc

2022-07-07 08:46 UTC, mucahit commented on src/modal/sign-toast/_pera-wallet-sign-txn-toast.scss
> +  position: absolute;
Shouldn't it be `position: fixed`?

2022-07-07 13:49 UTC, mucahit requested changes

2022-07-07 13:49 UTC, mucahit commented on README.md
> +`@perawallet/connect` informs users with toast when users try to sign transaction. If dApp wants to disable it, it can be disabled as follows. The default value of `shouldShowSignTxnToast` is `true`.
Let's move this paragraph under the `Sign Transaction` title after the first paragraph.

---

I'd also change a bit the paragraph


`@perawallet/connect` guides users with a toast message when the `signTransaction` is triggered. It's enabled by default but in some cases, you may not need to the toast message (e.g. you already have signing guidance for users). There's a configuration called `shouldShowSignTxnToast` to disable it, see the example below

```js
const peraWallet = new PeraWalletConnect({shouldShowSignTxnToast: false});
```

2022-07-07 13:49 UTC, mucahit commented on src/PeraWalletConnect.ts
> +    this.shouldShowSignTxnToast = options?.shouldShowSignTxnToast
How is this one?
```suggestion
    this.shouldShowSignTxnToast = typeof options?.shouldShowSignTxnToast === "undefined" 
    ? true : 
    options.shouldShowSignTxnToast
```

2022-07-07 14:18 UTC, mucahit approved these changes

2022-07-07 14:18 UTC, merged