fix(sign-txn): Solve ios app launch issue
perawallet/connect pull request #30
Opened 2022-07-19 10:24 UTC by yigiterdev

### Description
- On your first interaction (sign act) with the dApp browser asks you to "allow popups", if you allow it then it's all good if you don't allow it we'll show the redirect popup.
- There are some cases where Pera Wallet launches successfully but the redirect popup also shows up. 
- In some cases, safari can not ask permisson or redirect user to app. 

### Fixes
- We try to redirect users to app when they try to sign txn. In mobile safari, browser ask permission in every redirection try. But in other browsers, we successfully redirect user to mobile app. Check out the videos below.

  - Safari ->  https://user-images.githubusercontent.com/54077855/179728394-e96461e4-8710-43f3-a38f-fa8d0bfb76a5.MP4
  - Other Browsers(Opera) -> https://user-images.githubusercontent.com/54077855/179728471-c8076ea9-a71f-4fe3-85d2-3f22a1473868.MP4
  
- We solved the 3rd problem by changing the position of a condition

2022-07-19 10:30 UTC, yigiterdev commented on src/PeraWalletConnect.ts
> +        windowObj = window.open(PERA_WALLET_APP_DEEP_LINK, "_blank");
BTW, i'm not sure about naming. I'm open for suggestions.

2022-07-19 11:15 UTC, mucahit reviewed
thanks @yigiterdev this looks great

2022-07-19 11:15 UTC, mucahit commented on src/PeraWalletConnect.ts
> +      let windowObj;
```suggestion
      let peraWalletAppDeeplink;
```

2022-07-19 11:15 UTC, mucahit commented on src/PeraWalletConnect.ts
> +        windowObj = window.open(PERA_WALLET_APP_DEEP_LINK, "_blank");
Let's clean up inside of the `PeraWalletRedirectModal` component since we've moved the `window.open` stuff here.

2022-07-26 18:24 UTC, mucahit requested changes

2022-07-26 18:24 UTC, mucahit commented on src/PeraWalletConnect.ts
> +        peraWalletAppDeeplink = window.open(PERA_WALLET_APP_DEEP_LINK, "_blank");
Let's use `generatePeraWalletAppDeepLink()` utility

```suggestion
        peraWalletAppDeeplink = window.open(generatePeraWalletAppDeepLink(), "_blank");
```

2022-08-03 08:27 UTC, mucahit approved these changes

2022-08-05 20:25 UTC, merged